export const GET_USER_AUTHENTICATION = "GET_USER_AUTHENTICATION";
export const CLEAR_USER = "CLEAR_USER";
export const SIGN_IN_CLICKED = "SIGN_IN_CLICKED";
export const SET_GOLF_COURSE_LIST = "SET_GOLF_COURSE_LIST";
export const SET_SELECTED_COURSE = "SET_SELECTED_COURSE";
